# Generated by Django 3.2.16 on 2023-07-05 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230705_1743'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-is_published',), 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
