# Generated by Django 3.2.16 on 2023-07-16 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at', '-pub_date'), 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
